# Spring Boot + Spring LDAP configuration application.yml

spring:
  ldap:

    # Embedded Spring LDAP
    embedded:
      base-dn: dc=hazelcast,dc=com
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:schema.ldif
      port: 12345
      validation:
        enabled: false